services:
  - type: web
    name: huerting
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist/proyecto-final/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html